### ISSUE TITLE
为什么会字体不平整？简体会好过繁体一点

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-react#129]
如下图
![image](https://cloud.githubusercontent.com/assets/12795428/17439721/f3e3d3f6-5b5b-11e6-9769-98c7b408712d.png)

![image](https://cloud.githubusercontent.com/assets/12795428/17439738/08de806c-5b5c-11e6-80bf-8ca06645d153.png)

谢谢！

**Comment by minwe** [comment]
应该是字体的的原因，你自己设置一下试试：

```css
body {
  font-family: "HanHei TC","MHei","PingFang HK","STHeitiTC-Light", "Microsoft JhengHei", "Helvetica Neue","Helvetica","Arial",sans-serif;
}
```
