### ISSUE TITLE
使用了Navbar后，内容部分最后一点显示不全，有好的解决方法吗？

### ISSUE THREAD

**Issue by raywill** [amazeui/amazeui-react#62]
```react
      <div className="doc-example">
        <Header {...topNavData} />
        <Gallery data={shopItemData} />
        <Navbar data={bottomNavData} />
      </div>
```
Gallery最后一行的图片显示不全，被Navbar遮挡了。有什么好办法不让Gallery内容被遮挡吗？谢谢！

**Comment by minwe** [comment]
页面容器上加一个下边距：

```css
.doc-example {
  padding-bottom: 50px;
}
```

jQuery 版是自动加的，这里需要手动加一下。
